<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>msdl</string>
	</array>
	<key>name</key>
	<string>MSDL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(boolean|binary|decimal|double|float|int|int64|list|position|positiontime|set|text|timestamp|varint)\b</string>
			<key>name</key>
			<string>storage.type.msdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(namespace|include|enum|broadcast|message|endpoint)\b</string>
			<key>name</key>
			<string>keyword.control.msdl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.msdl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.msdl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.multi.msdl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.msdl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.single.msdl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.msdl</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.msdl</string>
	<key>uuid</key>
	<string>F30AAE86-5412-4CCF-A52B-0A953339644B</string>
</dict>
</plist>
